version: '3'
services:
    media_tidy_fingerprint:
      build: .
      container_name: lucos_media_tidy_fingerprint
      volumes:
        - "media:/medlib/import"
      environment:
        - MEDIA_API
      image: lucas42/lucos_media_tidy_fingerprint

volumes:
  media:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=aurora,ro,nolock,hard,intr,retry=3"
      device: ":/medlib/import"